import { requireAuth } from '../../../../lib/rbac/guards'
import { FileBarChart, Download, Calendar } from 'lucide-react'

/**
 * Client Portal Reports Page
 * Shows available reports for the authenticated client
 */
export default async function PortalReportsPage() {
  // Require authentication
  await requireAuth()

  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">Monthly Reports</h1>
        <p className="mt-2 text-gray-600">
          Access your monthly service reports including maintenance activities,
          incident summaries, and billing information.
        </p>
      </div>

      {/* Report Request Section */}
      <div className="bg-white rounded-lg border border-gray-200 p-6 mb-8">
        <div className="flex items-start space-x-4">
          <div className="flex-shrink-0">
            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
              <FileBarChart className="w-6 h-6 text-blue-600" />
            </div>
          </div>
          <div className="flex-1">
            <h2 className="text-xl font-semibold text-gray-900 mb-2">
              Request Monthly Report
            </h2>
            <p className="text-gray-600 mb-4">
              Monthly reports are generated by your account manager and will be
              delivered via email. Reports include detailed information about
              maintenance activities, incidents resolved, and billing summaries.
            </p>
            <div className="flex items-center space-x-4">
              <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors duration-200">
                Request Current Month Report
              </button>
              <span className="text-sm text-gray-500">
                Usually delivered within 1-2 business days
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Report Information */}
      <div className="grid md:grid-cols-2 gap-6 mb-8">
        <div className="bg-gray-50 rounded-lg p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-3">
            What&apos;s Included
          </h3>
          <ul className="space-y-2 text-sm text-gray-600">
            <li className="flex items-center space-x-2">
              <div className="w-1.5 h-1.5 bg-blue-600 rounded-full"></div>
              <span>Monthly rhythm activities breakdown</span>
            </li>
            <li className="flex items-center space-x-2">
              <div className="w-1.5 h-1.5 bg-blue-600 rounded-full"></div>
              <span>Incident tracking and resolution times</span>
            </li>
            <li className="flex items-center space-x-2">
              <div className="w-1.5 h-1.5 bg-blue-600 rounded-full"></div>
              <span>Service hours usage and allocation</span>
            </li>
            <li className="flex items-center space-x-2">
              <div className="w-1.5 h-1.5 bg-blue-600 rounded-full"></div>
              <span>Billing and invoice summaries</span>
            </li>
            <li className="flex items-center space-x-2">
              <div className="w-1.5 h-1.5 bg-blue-600 rounded-full"></div>
              <span>Performance metrics and insights</span>
            </li>
          </ul>
        </div>

        <div className="bg-gray-50 rounded-lg p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-3">
            Report Schedule
          </h3>
          <div className="space-y-3 text-sm text-gray-600">
            <div className="flex items-center space-x-3">
              <Calendar className="w-4 h-4 text-gray-400" />
              <span>Reports generated monthly after the 5th</span>
            </div>
            <div className="flex items-center space-x-3">
              <Download className="w-4 h-4 text-gray-400" />
              <span>Delivered as PDF via email</span>
            </div>
            <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-md">
              <p className="text-blue-800 text-xs">
                <strong>Note:</strong> Reports are generated using real-time
                data. For complete monthly summaries, reports are typically
                generated during the first week of the following month.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Coming Soon Section */}
      <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
        <h3 className="text-lg font-semibold text-yellow-800 mb-2">
          Coming Soon: Self-Service Reports
        </h3>
        <p className="text-yellow-700 text-sm mb-3">
          We&apos;re working on a feature that will allow you to generate and
          download your monthly reports directly from this portal. This will
          include:
        </p>
        <ul className="text-sm text-yellow-700 space-y-1">
          <li>• Instant PDF generation for any previous month</li>
          <li>• Historical report archive</li>
          <li>• Custom date range reporting</li>
          <li>• Automated monthly delivery options</li>
        </ul>
      </div>
    </div>
  )
}
